### ISSUE TITLE
Food Scraps

### ISSUE THREAD

**Issue by WesNz** [rusq/aklapi#10]
Not sure if this is a Auckland council api limitation or not...
How does one include the Food Scraps bin?

**Comment by rusq** [comment]
Hey, I'd be damned if I knew.  Can you see it on the Auckland Council website for your address?

Otherwise, maybe @sammcewan could advise?

**Comment by sammcewan** [comment]
I got you fam
```
- platform: rest
  resource: "http://localhost:5010/api/v1/rr/?addr=xx"
  name: Recycle
  scan_interval: 300
  value_template: "{{ value_json.recycle }}"
  method: GET
  unique_id: recycle_date

- platform: rest
  resource: "http://localhost:5010/api/v1/rr/?addr=xx"
  name: Food Scraps
  scan_interval: 300
  value_template: "{{ value_json.foodscraps }}"
  method: GET
  unique_id: foodscraps_date

- platform: rest
  resource: "http://localhost:5010/api/v1/rr/?addr=xx"
  name: Rubbish
  scan_interval: 300
  value_template: "{{ value_json.rubbish }}"
  method: GET
  unique_id: rubbish_date
  ```

Happy scrappin' 🍌

**Comment by rusq** [comment]
Oh that's what was the question 😂  Thank you @sammcewan !  @WesNz let me know if this solves this and I'll close the issue

**Comment by WesNz** [comment]
> Oh that's what was the question 😂 Thank you @sammcewan ! @WesNz let me know if this solves this and I'll close the issue

Great Thanks!
@rusq @sammcewan

**Comment by rusq** [comment]
Thanks for highlighting the fact that README is obscenely outdated, updated the example config in it (thanks Sam!)

**Comment by WesNz** [comment]
Wondering now if inorganics is available too :)

**Comment by rusq** [comment]
Inorganics are not implemented, but contributions are welcome :)
