### ISSUE TITLE
Returns 0001-01-01 for /api/v1/rr, and empty Collections for /api/v1/rrext

### ISSUE THREAD

**Issue by ndbroadbent** [rusq/aklapi#7]
Hi there, thanks for building this! I've been running it for a while, but occasionally see errors where it returns `0001-01-01` for the dates, which break my home assistant integration.

I just built and pushed the latest commit and deployed the Docker container. This is what I'm currently seeing:

```
curl "http://10.5.7.10:32769/api/v1/rr/?addr=MYADDRESS"
{"rubbish":"0001-01-01","recycle":"0001-01-01","foodscraps":"0001-01-01","address":"MYADDRESS"}

curl "http://10.5.7.10:32769/api/v1/rrext/?addr=MYADDRESS"
{"Collections":[],"Address":{"ACRateAccountKey":"*******","Address":"MYADDRESS","Suggestion":"MYADDRESS"}}
```

I checked the URL in a web browser and it's working fine:

https://www.aucklandcouncil.govt.nz/rubbish-recycling/rubbish-recycling-collections/Pages/collection-day-detail.aspx?an=****

Thanks!

**Comment by rusq** [comment]
Hey @ndbroadbent thanks reporting and resolving this.  What can be better than self-resolved issues 😂


For ancestors: follow up PR with tests, and bunch of minor updates #9

**Comment by rusq** [comment]
Tagged as v1.2.0
